import 'package:fit_shortcuts/models/models.dart';

const kItModules = ConfigModule(const Level(const [
  Subject("IN4910", SubjectMode.C, "Comprehensive Group Project", "https://online.uom.lk/course/view.php?id=18542"),
  Subject("IS3230", SubjectMode.C, "Social Aspects of IT", "https://online.uom.lk/course/view.php?id=18543"),
  Subject("IS3440", SubjectMode.C, "IT Quality Assurance", "https://online.uom.lk/course/view.php?id=18545"),
  Subject("CM4340", SubjectMode.E, "Natural Language Processing", "https://online.uom.lk/course/view.php?id=18526"),
  Subject("IN4620", SubjectMode.E, "Digital Image Processing", "https://online.uom.lk/course/view.php?id=18535"),
  Subject("IN4700", SubjectMode.E, "Cluster Computing", "https://online.uom.lk/course/view.php?id=18536"),
  Subject("IN4710", SubjectMode.E, "Human Computer Interaction", "https://online.uom.lk/course/view.php?id=18538"),
  Subject("IN4300", SubjectMode.E, "Embedded Systems", "https://online.uom.lk/course/view.php?id=18532"),
  Subject("IN4400", SubjectMode.E, "Data Mining & Data Warehousing", "https://online.uom.lk/course/view.php?id=18533"),
  Subject("IN4720", SubjectMode.E, "Geographic Information Systems", "https://online.uom.lk/course/view.php?id=18540"),
  Subject("CM4140", SubjectMode.E, "Operational Research", "https://online.uom.lk/course/view.php?id=18518"),
  Subject("CM4310", SubjectMode.E, "Artificial Neural Networks & Evolutionary Computing", "https://online.uom.lk/course/view.php?id=18520"),
  Subject("CM4320", SubjectMode.E, "Complex Systems & Agent Technology", "https://online.uom.lk/course/view.php?id=18522"),
  Subject("CM4330", SubjectMode.E, "Semantic Web and Ontological Modelling", "https://online.uom.lk/course/view.php?id=18524"),
  Subject("CM4360", SubjectMode.E, "Robotics", "https://online.uom.lk/course/view.php?id=18528"),
  Subject("CM4370", SubjectMode.E, "Machine Learning and Pattern Recognition", "https://online.uom.lk/course/view.php?id=18530"),
  Subject("IS4300", SubjectMode.E, "Marketing Management", "https://online.uom.lk/course/view.php?id=18547"),
  Subject("IS4330", SubjectMode.E, "Supply Chain Management", "https://online.uom.lk/course/view.php?id=18549"),
  Subject("IS4340", SubjectMode.E, "Innovation Management", "https://online.uom.lk/course/view.php?id=18516"),
  Subject("IS4400", SubjectMode.E, "Management of Technology", "https://online.uom.lk/course/view.php?id=18551"),
  Subject(
    "CM 3320",
    SubjectMode.C,
    "Logic Programming & Artificial Cognitive Systems",
    "https://moodle.itfac.uom.lk/course/view.php?id=1997",
  ),
  Subject(
    "CM 3310",
    SubjectMode.C,
    "Artificial Intelligence",
    "https://moodle.itfac.uom.lk/course/view.php?id=1996",
  ),
  Subject(
    "CM 3120",
    SubjectMode.E,
    "Computational Statistics",
    "https://moodle.itfac.uom.lk/course/view.php?id=1995",
  ),
  Subject(
    "CM 3210",
    SubjectMode.E,
    "Automata Theory",
    "https://moodle.itfac.uom.lk/course/view.php?id=1994",
  ),
  Subject(
    "CM 3110",
    SubjectMode.E,
    "Computational Mathematics",
    "https://moodle.itfac.uom.lk/course/view.php?id=1993",
  ),
  Subject(
    "CM 3330",
    SubjectMode.E,
    "Fundamentals of Bio informatics",
    "https://moodle.itfac.uom.lk/course/view.php?id=1992",
  ),
  Subject(
    "IS 3430",
    SubjectMode.C,
    "IT Project Management",
    "https://moodle.itfac.uom.lk/course/view.php?id=1985",
  ),
  Subject(
    "IS 3100",
    SubjectMode.E,
    "Organizational Behavior",
    "https://moodle.itfac.uom.lk/course/view.php?id=1984",
  ),
  Subject(
    "IS 3400",
    SubjectMode.C,
    "Management Information Systems",
    "https://moodle.itfac.uom.lk/course/view.php?id=1983",
  ),
  Subject(
    "IS 4310",
    SubjectMode.E,
    "Business Studies",
    "https://moodle.itfac.uom.lk/course/view.php?id=1982",
  ),
  Subject(
    "IS 4320",
    SubjectMode.E,
    "eBusiness Management",
    "https://moodle.itfac.uom.lk/course/view.php?id=1980",
  ),
  Subject(
    "IS 3010",
    SubjectMode.C,
    "Communication Skills",
    "https://moodle.itfac.uom.lk/course/view.php?id=1979",
  ),
  Subject(
    "IN 4500",
    SubjectMode.E,
    "Mobile & Wireless Networks",
    "https://moodle.itfac.uom.lk/course/view.php?id=1990",
  ),
  Subject(
    "IN 3100",
    SubjectMode.E,
    "Enterprise Applications Development",
    "https://moodle.itfac.uom.lk/course/view.php?id=1989",
  ),
  Subject(
    "IN 4110",
    SubjectMode.E,
    "Network Programming",
    "https://moodle.itfac.uom.lk/course/view.php?id=1988",
  ),
  Subject(
    "IN 3400",
    SubjectMode.E,
    "Advanced Database Management Systems",
    "https://moodle.itfac.uom.lk/course/view.php?id=1987",
  ),
  Subject(
    "IN 3900",
    SubjectMode.C,
    "Independent Study",
    "https://moodle.itfac.uom.lk/course/view.php?id=1986",
  ),
  Subject(
    "IS 3910",
    SubjectMode.C,
    "Independent Study (ITM)",
    "https://moodle.itfac.uom.lk/course/view.php?id=1977",
  ),
  Subject(
    "IS 4420",
    SubjectMode.E,
    "Decision Management",
    "https://moodle.itfac.uom.lk/course/view.php?id=1981",
  ),
], null));
